swagger: '2.0'
info:
  title: ExCell Integration Layer
  description: >-
    API Dokumentation für die ExCell Integration Layer.
    Die sogenannte Integration Layer bietet dem Entwickler eine Schnittstelle zu den 
    verschiedenen Services. Über einen Signup kann ein Account erstellt werden. Diesem
    Account wird ein Webtoken zugeordnet, der über den Authorisierungsendpoint abgerufen
    werden kann. Dieser Token ist nötig, um sich auf der Integration Layer und den einzelnen
    Services zu authorisieren.
    Die Integration Layer selbst bietet darüber hinaus weitere Möglichkeiten.
    Zum Beispiel kann die Anzahl an Requests zu den verschiedenen Services innerhalb einer gewissen
    Periode aufgerufen werden. Des weiteren können die momentanen Berechtigungen eingesehen werden.
  version: 1.0.0
host: 'dlr-integration.minglabs.com'
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /tokenauth/:
    post:
      summary: Fetches user webtoken
      description: >-
        Returns the webtoken for the user to authenticate with the server. The
        token has to be passed in every request in the 'Authorization' Header
        with the value 'Token #token#', where '#token#' is the retrieved token. 
      parameters:
        - in: body
          name: body
          description: Fetches user webtoken
          required: true
          schema:
            $ref: '#/definitions/UserToken'
      tags:
        - user
      responses:
        '200':
          description: success - valid token retrieved
        '201':
          description: success - new valid token generated and retrieved
        '400':
          description: >-
            Bad request - Either the user does not exist or the password does
            not match to the user
  /tokenauth/clients/:
    get:
      summary: Show all User-Agents for valid tokens
      description: >-
        For different user-agents there are different tokens. With this endpoint
        one can retrieve all user-agents for all valid tokens.
      tags:
        - user
      responses:
        '200':
          description: success
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
      security:
        - api_key: []
  /tokenauth/logout-all/:
    post:
      summary: Invalidates all token user-agent combinations
      tags:
        - user
      responses:
        '200':
          description: success
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
      security:
        - api_key: []
  /tokenauth/change-password/:
    post:
      summary: Changes user password
      parameters:
        - in: body
          name: body
          description: old and new password
          required: true
          schema:
            $ref: '#/definitions/UserChangePassword'
      tags:
        - user
      responses:
        '200':
          description: success
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
  /tokenauth/signup/:
    post:
      summary: Signup for new user
      parameters:
        - in: body
          name: body
          description: Basic signup data
          required: true
          schema:
            $ref: '#/definitions/UserSignup'
      tags:
        - user
      responses:
        '201':
          description: success - user and token created
        '400':
          description: >-
            Bad request - Username not available, or wrong username- / email format.
  /report/service-requests/:
    get:
      summary: Returns the amount of requests to each service.
      description: >-
        Returns the amount of requests to each service in the given date range. 
      tags:
        - client
      parameters:
        - in: query
          name: start_date
          description: date in 2017-09-14 (YYYY-MM-DD)
          required: true
          type: string
        - in: query
          name: end_date
          description: date in 2017-09-14 (YYYY-MM-DD)
          required: true
          type: string
      responses:
        '200':
          description: success
        '400':
          description: Bad request
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
      security:
        - api_key: []
  /access/services/:
    get:
      summary: Returns the services the user has access to.
      tags:
        - client
      responses:
        '200':
          description: success
        '400':
          description: Bad request
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
      security:
        - api_key: []
  /report/client-requests/:
    get:
      summary: Returns the amount of requests from each client.
      description: >-
        Returns the amount of requests from each client in the given date
        range. 
      tags:
        - service
      parameters:
        - in: query
          name: start_date
          description: date in 2017-09-14 (YYYY-MM-DD)
          required: true
          type: string
        - in: query
          name: end_date
          description: date in 2017-09-14 (YYYY-MM-DD)
          required: true
          type: string
      responses:
        '200':
          description: success
        '400':
          description: Bad request
        '401':
          description: >-
            unauthorized - authentication credentials were not provided or
            invalid
      security:
        - api_key: []
definitions:
  UserToken:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  UserSignup:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      company:
        type: string
      phone_number:
        type: string
      position:
        type: string
  UserChangePassword:
    type: object
    properties:
      old_password:
        type: string
      password:
        type: string
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
